all:
	iverilog -o AluAdder tbadder_alu.v
	iverilog -o AluAnd tband_alu.v
	iverilog -o Aluor tbor_alu.v
	iverilog -o Alunor tbnor_alu.v
	iverilog -o Aluxor tbxor_alu.v
	iverilog -o AluSub tbsub_alu.v 
